### ISSUE TITLE
HistoryRequest 是None

### ISSUE THREAD

**Issue by dalitang** [vnpy/vnpy_ib#13]
`Exception in thread Thread-9 (run):
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/ibapi/client.py", line 263, in run
    self.decoder.interpret(fields)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/ibapi/decoder.py", line 1296, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/ibapi/decoder.py", line 519, in processHistoricalDataMsg
    self.wrapper.historicalData(reqId, bar)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages/vnpy_ib/ib_gateway.py", line 619, in historicalData
    symbol=self.history_req.symbol,
AttributeError: 'NoneType' object has no attribute 'symbol'`

这个应该是api返回了None或者是还没有等到返回值？

**Comment by dalitang** [comment]
我在line 618 前面加了一行：
`while self.history_req is None: sleep(0.1)`
多试几次就可以成功的下载了

**Comment by noranhe** [comment]
可参考https://github.com/vnpy/vnpy_ib/issues/12

**Comment by noranhe** [comment]
可参考 https://github.com/vnpy/vnpy_ib/issues/12 最新回复
